import { fetchPosts } from '../utils/api';

export default async function sitemap() {
  const baseUrl = 'https://fsan.com';

  // 1. Define your core, static landing pages
  const staticRoutes = [
    '',
    '/home',
    '/subscribe',
    '/rankings',
    '/football/home',
    '/football/articles',
    '/football/videos',
    '/football/podcasts',
    '/football/rankings',
    '/football/teams',
    '/football/jersey-leagues',
    '/basketball/home',
    '/baseball/home'
  ].map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date().toISOString(),
    changeFrequency: 'daily',
    priority: route === '' ? 1.0 : 0.8,
  }));

  let dynamicRoutes = [];

  try {
    // 2. Fetch the most recent pages of content from your WordPress API
    // We fetch the first 4 pages (roughly 300+ of your newest posts) to prioritize Google's crawl budget
    const pagesToFetch = [1, 2, 3, 4];
    const fetchPromises = pagesToFetch.map(page => fetchPosts('All', 'all', page));
    const results = await Promise.all(fetchPromises);

    const allPosts = results.flatMap(res => res.posts || []);

    // Deduplicate posts by ID just to be safe
    const uniquePosts = Array.from(new Map(allPosts.map(p => [p.id, p])).values());

    // 3. Map the WordPress posts into perfectly formatted frontend URLs
    dynamicRoutes = uniquePosts.map((post) => {
      // Use the exact same URL building logic you use in your UI
      const sportPath = (!post.sport || post.sport === 'All') ? 'football' : post.sport.toLowerCase();
      const typePath = post.type ? `${post.type}s` : 'articles';
      
      return {
        url: `${baseUrl}/${sportPath}/${typePath}/${post.slug}`,
        // Use the raw timestamp generated by your api.js file
        lastModified: post.rawTimestamp ? new Date(post.rawTimestamp).toISOString() : new Date().toISOString(),
        changeFrequency: 'weekly',
        priority: 0.6,
      };
    });
  } catch (error) {
    console.error("Sitemap generation error:", error);
  }

  // Combine static pages and dynamic posts into one massive XML list!
  return [...staticRoutes, ...dynamicRoutes];
}