export const OFFSEASON_FUTURES_DATABASE = [
    // === QUARTERBACKS ===
    { name: "Jared Goff", position: "QB", team: null, age: null, pass_yds: 4099.5, pass_tds: 29.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Matthew Stafford", position: "QB", team: null, age: null, pass_yds: 3999.5, pass_tds: 30.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Dak Prescott", position: "QB", team: null, age: null, pass_yds: 3999.5, pass_tds: 27.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Joe Burrow", position: "QB", team: null, age: null, pass_yds: 3999.5, pass_tds: 32.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Brock Purdy", position: "QB", team: null, age: null, pass_yds: 3799.5, pass_tds: 27.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Drake Maye", position: "QB", team: null, age: null, pass_yds: 3799.5, pass_tds: 26.5, ints: 0, rush_yds: 424.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Trevor Lawrence", position: "QB", team: null, age: null, pass_yds: 3749.5, pass_tds: 25.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Sam Darnold", position: "QB", team: null, age: null, pass_yds: 3749.5, pass_tds: 23.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "C.J. Stroud", position: "QB", team: null, age: null, pass_yds: 3649.5, pass_tds: 22.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Tyler Shough", position: "QB", team: null, age: null, pass_yds: 3649.5, pass_tds: 20.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Caleb Williams", position: "QB", team: null, age: null, pass_yds: 3624.5, pass_tds: 24.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Baker Mayfield", position: "QB", team: null, age: null, pass_yds: 3599.5, pass_tds: 25.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Justin Herbert", position: "QB", team: null, age: null, pass_yds: 3574.5, pass_tds: 24.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Josh Allen", position: "QB", team: null, age: null, pass_yds: 3549.5, pass_tds: 24.5, ints: 0, rush_yds: 499.5, rush_tds: 11.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Jordan Love", position: "QB", team: null, age: null, pass_yds: 3549.5, pass_tds: 24.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Bo Nix", position: "QB", team: null, age: null, pass_yds: 3499.5, pass_tds: 24.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Cameron Ward", position: "QB", team: null, age: null, pass_yds: 3299.5, pass_tds: 18.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Jayden Daniels", position: "QB", team: null, age: null, pass_yds: 3249.5, pass_tds: 21.5, ints: 0, rush_yds: 549.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Lamar Jackson", position: "QB", team: null, age: null, pass_yds: 3249.5, pass_tds: 24.5, ints: 0, rush_yds: 574.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Jalen Hurts", position: "QB", team: null, age: null, pass_yds: 3249.5, pass_tds: 22.5, ints: 0, rush_yds: 399.5, rush_tds: 8.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Aaron Rodgers", position: "QB", team: null, age: null, pass_yds: 3199.5, pass_tds: 21.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Jaxson Dart", position: "QB", team: null, age: null, pass_yds: 3150.5, pass_tds: 19.5, ints: 0, rush_yds: 449.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Bryce Young", position: "QB", team: null, age: null, pass_yds: 3074.5, pass_tds: 20.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Malik Willis", position: "QB", team: null, age: null, pass_yds: 3050.5, pass_tds: 15.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Fernando Mendoza", position: "QB", team: null, age: null, pass_yds: 2399.5, pass_tds: 12.5, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
  
    // === RUNNING BACKS ===
    { name: "Derrick Henry", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1274.5, rush_tds: 12.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Jahmyr Gibbs", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1249.5, rush_tds: 12.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "James Cook", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1249.5, rush_tds: 10.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Jonathan Taylor", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1249.5, rush_tds: 11.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Bijan Robinson", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1174.5, rush_tds: 8.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Saquon Barkley", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1099.5, rush_tds: 7.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Ashton Jeanty", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1024.5, rush_tds: 7.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Javonte Williams", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 999.5, rush_tds: 9.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Kyren Williams", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 999.5, rush_tds: 9.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "De'Von Achane", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 999.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Christian McCaffrey", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 974.5, rush_tds: 8.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Omarion Hampton", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 949.5, rush_tds: 7.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Kenneth Walker III", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 924.5, rush_tds: 7.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Breece Hall", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 899.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Jeremiyah Love", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 899.5, rush_tds: 5.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Chase Brown", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 824.5, rush_tds: 5.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "D'Andre Swift", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 799.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Tony Pollard", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 799.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "David Montgomery", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 774.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Bhayshul Tuten", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 699.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
    { name: "Blake Corum", position: "RB", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 674.5, rush_tds: 0, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 0 },
  
    // === WIDE RECEIVERS ===
    { name: "Puka Nacua", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1324.5, rec_tds: 7.5, fumbles: 0 },
    { name: "Jaxon Smith-Njigba", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1324.5, rec_tds: 8.5, fumbles: 0 },
    { name: "Ja'Marr Chase", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1324.5, rec_tds: 10.5, fumbles: 0 },
    { name: "Amon-Ra St. Brown", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1249.5, rec_tds: 9.5, fumbles: 0 },
    { name: "CeeDee Lamb", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1199.5, rec_tds: 7.5, fumbles: 0 },
    { name: "Drake London", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1149.5, rec_tds: 7.5, fumbles: 0 },
    { name: "Justin Jefferson", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1149.5, rec_tds: 6.5, fumbles: 0 },
    { name: "A.J. Brown", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1124.5, rec_tds: 0, fumbles: 0 },
    { name: "Nico Collins", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1074.5, rec_tds: 6.5, fumbles: 0 },
    { name: "DeVonta Smith", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1049.5, rec_tds: 0, fumbles: 0 },
    { name: "Chris Olave", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 1024.5, rec_tds: 5.5, fumbles: 0 },
    { name: "Garrett Wilson", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 999.5, rec_tds: 0, fumbles: 0 },
    { name: "George Pickens", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 999.5, rec_tds: 6.5, fumbles: 0 },
    { name: "Zay Flowers", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 974.5, rec_tds: 0, fumbles: 0 },
    { name: "Tetairoa McMillan", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 949.5, rec_tds: 6.5, fumbles: 0 },
    { name: "Terry McLaurin", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 949.5, rec_tds: 0, fumbles: 0 },
    { name: "Mike Evans", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 899.5, rec_tds: 0, fumbles: 0 },
    { name: "Alec Pierce", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 899.5, rec_tds: 0, fumbles: 0 },
    { name: "Jameson Williams", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 899.5, rec_tds: 0, fumbles: 0 },
    { name: "Emeka Egbuka", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 874.5, rec_tds: 0, fumbles: 0 },
    { name: "Tee Higgins", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 874.5, rec_tds: 8.5, fumbles: 0 },
    { name: "Jaylen Waddle", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 874.5, rec_tds: 0, fumbles: 0 },
    { name: "Ladd McConkey", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 849.5, rec_tds: 0, fumbles: 0 },
    { name: "Luther Burden III", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 824.5, rec_tds: 0, fumbles: 0 },
    { name: "DK Metcalf", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 824.5, rec_tds: 0, fumbles: 0 },
    { name: "Marvin Harrison Jr.", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 824.5, rec_tds: 0, fumbles: 0 },
    { name: "DJ Moore", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 799.5, rec_tds: 0, fumbles: 0 },
    { name: "Rome Odunze", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 799.5, rec_tds: 0, fumbles: 0 },
    { name: "Courtland Sutton", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 799.5, rec_tds: 0, fumbles: 0 },
    { name: "Christian Watson", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 799.5, rec_tds: 0, fumbles: 0 },
    { name: "Michael Pittman Jr.", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 774.5, rec_tds: 0, fumbles: 0 },
    { name: "Davante Adams", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 774.5, rec_tds: 9.5, fumbles: 0 },
    { name: "Jordyn Tyson", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 774.5, rec_tds: 0, fumbles: 0 },
    { name: "Carnell Tate", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 774.5, rec_tds: 0, fumbles: 0 },
    { name: "Brian Thomas Jr.", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 724.5, rec_tds: 0, fumbles: 0 },
    { name: "Khalil Shakir", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 674.5, rec_tds: 0, fumbles: 0 },
    { name: "Jordan Addison", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 674.5, rec_tds: 0, fumbles: 0 },
    { name: "Jayden Reed", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 649.5, rec_tds: 0, fumbles: 0 },
    { name: "Josh Downs", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 649.5, rec_tds: 0, fumbles: 0 },
    { name: "Makai Lemon", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 649.5, rec_tds: 0, fumbles: 0 },
    { name: "KC Concepcion", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 624.5, rec_tds: 0, fumbles: 0 },
    { name: "Omar Cooper Jr.", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 549.5, rec_tds: 0, fumbles: 0 },
    { name: "Denzel Boston", position: "WR", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 474.5, rec_tds: 0, fumbles: 0 },
  
    // === TIGHT ENDS ===
    { name: "Trey McBride", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 999.5, rec_tds: 6.5, fumbles: 0 },
    { name: "Brock Bowers", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 899.5, rec_tds: 7.5, fumbles: 0 },
    { name: "Kyle Pitts", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 774.5, rec_tds: 0, fumbles: 0 },
    { name: "Colston Loveland", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 749.5, rec_tds: 0, fumbles: 0 },
    { name: "Tyler Warren", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 724.5, rec_tds: 0, fumbles: 0 },
    { name: "Travis Kelce", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 674.5, rec_tds: 4.5, fumbles: 0 },
    { name: "Dallas Goedert", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 574.5, rec_tds: 0, fumbles: 0 },
    { name: "Dalton Kincaid", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 549.5, rec_tds: 0, fumbles: 0 },
    { name: "Mark Andrews", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 524.5, rec_tds: 0, fumbles: 0 },
    { name: "Jake Ferguson", position: "TE", team: null, age: null, pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 0, rec_yds: 524.5, rec_tds: 0, fumbles: 0 }
  ];