// 🏈 REAL VEGAS OFF-SEASON FUTURES & ESTIMATES 
// Cleaned, Deduplicated, and Updated for the Upcoming Season
// Added the `team` property for dynamic ESPN Logo rendering

export const OFFSEASON_FUTURES_DATABASE = [
    // --- QUARTERBACKS ---
    { name: "Josh Allen", team: "buf", position: "QB", pass_yds: 3950.5, pass_tds: 29.5, ints: 13.5, rush_yds: 525.5, rush_tds: 8.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 4 },
    { name: "Patrick Mahomes", team: "kc", position: "QB", pass_yds: 4250.5, pass_tds: 32.5, ints: 11.5, rush_yds: 350.5, rush_tds: 2.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 3 },
    { name: "Jalen Hurts", team: "phi", position: "QB", pass_yds: 3650.5, pass_tds: 23.5, ints: 12.5, rush_yds: 600.5, rush_tds: 11.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 4 },
    { name: "Lamar Jackson", team: "bal", position: "QB", pass_yds: 3500.5, pass_tds: 22.5, ints: 9.5, rush_yds: 800.5, rush_tds: 5.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 5 },
    { name: "C.J. Stroud", team: "hou", position: "QB", pass_yds: 4350.5, pass_tds: 29.5, ints: 9.5, rush_yds: 150.5, rush_tds: 2.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 3 },
    { name: "Joe Burrow", team: "cin", position: "QB", pass_yds: 4150.5, pass_tds: 30.5, ints: 10.5, rush_yds: 125.5, rush_tds: 1.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 2 },
    { name: "Anthony Richardson", team: "ind", position: "QB", pass_yds: 3200.5, pass_tds: 19.5, ints: 13.5, rush_yds: 700.5, rush_tds: 8.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 4 },
    { name: "Dak Prescott", team: "dal", position: "QB", pass_yds: 4200.5, pass_tds: 31.5, ints: 10.5, rush_yds: 150.5, rush_tds: 2.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 2 },
    { name: "Jordan Love", team: "gb", position: "QB", pass_yds: 4050.5, pass_tds: 29.5, ints: 11.5, rush_yds: 200.5, rush_tds: 2.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 2 },
    { name: "Kyler Murray", team: "ari", position: "QB", pass_yds: 3600.5, pass_tds: 22.5, ints: 10.5, rush_yds: 550.5, rush_tds: 4.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 3 },
    { name: "Brock Purdy", team: "sf", position: "QB", pass_yds: 4100.5, pass_tds: 28.5, ints: 10.5, rush_yds: 150.5, rush_tds: 2.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 1 },
    { name: "Tua Tagovailoa", team: "mia", position: "QB", pass_yds: 4250.5, pass_tds: 27.5, ints: 12.5, rush_yds: 50.5, rush_tds: 0.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 3 },
    { name: "Jared Goff", team: "det", position: "QB", pass_yds: 4150.5, pass_tds: 27.5, ints: 10.5, rush_yds: 25.5, rush_tds: 1.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 3 },
    { name: "Justin Herbert", team: "lac", position: "QB", pass_yds: 3900.5, pass_tds: 25.5, ints: 9.5, rush_yds: 200.5, rush_tds: 2.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 2 },
    { name: "Caleb Williams", team: "chi", position: "QB", pass_yds: 3650.5, pass_tds: 23.5, ints: 12.5, rush_yds: 350.5, rush_tds: 3.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 3 },
    { name: "Jayden Daniels", team: "wsh", position: "QB", pass_yds: 3200.5, pass_tds: 17.5, ints: 11.5, rush_yds: 700.5, rush_tds: 6.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 4 },
    { name: "Trevor Lawrence", team: "jax", position: "QB", pass_yds: 4000.5, pass_tds: 24.5, ints: 12.5, rush_yds: 300.5, rush_tds: 3.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 5 },
    { name: "Kirk Cousins", team: "atl", position: "QB", pass_yds: 4050.5, pass_tds: 27.5, ints: 10.5, rush_yds: 25.5, rush_tds: 1.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 3 },
    { name: "Aaron Rodgers", team: "nyj", position: "QB", pass_yds: 3950.5, pass_tds: 28.5, ints: 9.5, rush_yds: 40.5, rush_tds: 0.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 2 },
    { name: "Matthew Stafford", team: "lar", position: "QB", pass_yds: 4050.5, pass_tds: 26.5, ints: 12.5, rush_yds: 25.5, rush_tds: 0.5, receptions: 0, rec_yds: 0, rec_tds: 0, fumbles: 2 },
  
    // --- RUNNING BACKS ---
    { name: "Christian McCaffrey", team: "sf", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1150.5, rush_tds: 10.5, receptions: 65.5, rec_yds: 550.5, rec_tds: 4.5, fumbles: 2 },
    { name: "Breece Hall", team: "nyj", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1100.5, rush_tds: 8.5, receptions: 65.5, rec_yds: 525.5, rec_tds: 3.5, fumbles: 2 },
    { name: "Bijan Robinson", team: "atl", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1125.5, rush_tds: 8.5, receptions: 60.5, rec_yds: 500.5, rec_tds: 3.5, fumbles: 2 },
    { name: "Jahmyr Gibbs", team: "det", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 950.5, rush_tds: 8.5, receptions: 60.5, rec_yds: 475.5, rec_tds: 3.5, fumbles: 1 },
    { name: "Jonathan Taylor", team: "ind", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1200.5, rush_tds: 9.5, receptions: 35.5, rec_yds: 275.5, rec_tds: 1.5, fumbles: 2 },
    { name: "Saquon Barkley", team: "phi", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1150.5, rush_tds: 8.5, receptions: 45.5, rec_yds: 325.5, rec_tds: 2.5, fumbles: 1 },
    { name: "Kyren Williams", team: "lar", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1050.5, rush_tds: 9.5, receptions: 40.5, rec_yds: 250.5, rec_tds: 2.5, fumbles: 2 },
    { name: "Travis Etienne Jr.", team: "jax", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1000.5, rush_tds: 8.5, receptions: 50.5, rec_yds: 400.5, rec_tds: 1.5, fumbles: 2 },
    { name: "Derrick Henry", team: "bal", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1150.5, rush_tds: 11.5, receptions: 15.5, rec_yds: 125.5, rec_tds: 0.5, fumbles: 2 },
    { name: "Isiah Pacheco", team: "kc", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1050.5, rush_tds: 8.5, receptions: 40.5, rec_yds: 250.5, rec_tds: 1.5, fumbles: 2 },
    { name: "Josh Jacobs", team: "gb", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1050.5, rush_tds: 7.5, receptions: 35.5, rec_yds: 250.5, rec_tds: 1.5, fumbles: 1 },
    { name: "Rachaad White", team: "tb", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 950.5, rush_tds: 6.5, receptions: 60.5, rec_yds: 500.5, rec_tds: 2.5, fumbles: 2 },
    { name: "James Cook", team: "buf", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1000.5, rush_tds: 5.5, receptions: 45.5, rec_yds: 400.5, rec_tds: 2.5, fumbles: 2 },
    { name: "Alvin Kamara", team: "no", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 750.5, rush_tds: 5.5, receptions: 70.5, rec_yds: 500.5, rec_tds: 2.5, fumbles: 1 },
    { name: "Joe Mixon", team: "hou", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1000.5, rush_tds: 8.5, receptions: 45.5, rec_yds: 350.5, rec_tds: 2.5, fumbles: 1 },
    { name: "Kenneth Walker III", team: "sea", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1050.5, rush_tds: 9.5, receptions: 30.5, rec_yds: 225.5, rec_tds: 1.5, fumbles: 1 },
    { name: "Aaron Jones", team: "min", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 900.5, rush_tds: 6.5, receptions: 45.5, rec_yds: 350.5, rec_tds: 3.5, fumbles: 2 },
    { name: "James Conner", team: "ari", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 900.5, rush_tds: 8.5, receptions: 30.5, rec_yds: 200.5, rec_tds: 1.5, fumbles: 1 },
    { name: "D'Andre Swift", team: "chi", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 900.5, rush_tds: 6.5, receptions: 45.5, rec_yds: 325.5, rec_tds: 2.5, fumbles: 2 },
    { name: "David Montgomery", team: "det", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 900.5, rush_tds: 10.5, receptions: 20.5, rec_yds: 150.5, rec_tds: 0.5, fumbles: 1 },
    { name: "Najee Harris", team: "pit", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 1000.5, rush_tds: 7.5, receptions: 35.5, rec_yds: 225.5, rec_tds: 1.5, fumbles: 1 },
    { name: "Rhamondre Stevenson", team: "ne", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 900.5, rush_tds: 6.5, receptions: 45.5, rec_yds: 300.5, rec_tds: 1.5, fumbles: 2 },
    { name: "Jaylen Warren", team: "pit", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 700.5, rush_tds: 4.5, receptions: 55.5, rec_yds: 400.5, rec_tds: 1.5, fumbles: 1 },
    { name: "Tony Pollard", team: "ten", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 800.5, rush_tds: 6.5, receptions: 45.5, rec_yds: 300.5, rec_tds: 1.5, fumbles: 2 },
    { name: "Austin Ekeler", team: "wsh", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 600.5, rush_tds: 5.5, receptions: 50.5, rec_yds: 400.5, rec_tds: 2.5, fumbles: 2 },
    { name: "Zamir White", team: "lv", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 900.5, rush_tds: 7.5, receptions: 30.5, rec_yds: 200.5, rec_tds: 1.5, fumbles: 1 },
    { name: "Jonathon Brooks", team: "car", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 800.5, rush_tds: 6.5, receptions: 35.5, rec_yds: 250.5, rec_tds: 1.5, fumbles: 1 },
    { name: "Brian Robinson Jr.", team: "wsh", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 850.5, rush_tds: 7.5, receptions: 30.5, rec_yds: 250.5, rec_tds: 1.5, fumbles: 1 },
    { name: "Zack Moss", team: "cin", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 800.5, rush_tds: 6.5, receptions: 25.5, rec_yds: 175.5, rec_tds: 1.5, fumbles: 1 },
    { name: "Devin Singletary", team: "nyg", position: "RB", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 850.5, rush_tds: 6.5, receptions: 30.5, rec_yds: 200.5, rec_tds: 1.5, fumbles: 2 },
  
    // --- WIDE RECEIVERS ---
    { name: "CeeDee Lamb", team: "dal", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 50.5, rush_tds: 0.5, receptions: 115.5, rec_yds: 1450.5, rec_tds: 10.5, fumbles: 1 },
    { name: "Tyreek Hill", team: "mia", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 15.5, rush_tds: 0, receptions: 110.5, rec_yds: 1475.5, rec_tds: 10.5, fumbles: 1 },
    { name: "Justin Jefferson", team: "min", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 108.5, rec_yds: 1500.5, rec_tds: 9.5, fumbles: 1 },
    { name: "Amon-Ra St. Brown", team: "det", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 10.5, rush_tds: 0, receptions: 112.5, rec_yds: 1350.5, rec_tds: 9.5, fumbles: 1 },
    { name: "Ja'Marr Chase", team: "cin", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 100.5, rec_yds: 1400.5, rec_tds: 10.5, fumbles: 1 },
    { name: "A.J. Brown", team: "phi", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 95.5, rec_yds: 1350.5, rec_tds: 8.5, fumbles: 1 },
    { name: "Puka Nacua", team: "lar", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 50.5, rush_tds: 0, receptions: 100.5, rec_yds: 1300.5, rec_tds: 8.5, fumbles: 1 },
    { name: "Garrett Wilson", team: "nyj", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 98.5, rec_yds: 1250.5, rec_tds: 8.5, fumbles: 1 },
    { name: "Marvin Harrison Jr.", team: "ari", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 85.5, rec_yds: 1150.5, rec_tds: 7.5, fumbles: 0 },
    { name: "Drake London", team: "atl", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 88.5, rec_yds: 1150.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Chris Olave", team: "no", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 85.5, rec_yds: 1150.5, rec_tds: 6.5, fumbles: 1 },
    { name: "Davante Adams", team: "lv", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 90.5, rec_yds: 1050.5, rec_tds: 8.5, fumbles: 1 },
    { name: "Mike Evans", team: "tb", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 78.5, rec_yds: 1100.5, rec_tds: 10.5, fumbles: 0 },
    { name: "Deebo Samuel", team: "sf", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 225.5, rush_tds: 3.5, receptions: 62.5, rec_yds: 850.5, rec_tds: 6.5, fumbles: 2 },
    { name: "Brandon Aiyuk", team: "sf", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 75.5, rec_yds: 1150.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Michael Pittman Jr.", team: "ind", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 100.5, rec_yds: 1050.5, rec_tds: 6.5, fumbles: 1 },
    { name: "Jaylen Waddle", team: "mia", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 80.5, rec_yds: 1050.5, rec_tds: 7.5, fumbles: 1 },
    { name: "DJ Moore", team: "chi", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 85.5, rec_yds: 1100.5, rec_tds: 7.5, fumbles: 1 },
    { name: "DeVonta Smith", team: "phi", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 85.5, rec_yds: 1100.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Stefon Diggs", team: "hou", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 88.5, rec_yds: 1000.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Malik Nabers", team: "nyg", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 25.5, rush_tds: 0, receptions: 80.5, rec_yds: 1050.5, rec_tds: 6.5, fumbles: 1 },
    { name: "DK Metcalf", team: "sea", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 75.5, rec_yds: 1050.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Cooper Kupp", team: "lar", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 85.5, rec_yds: 1050.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Amari Cooper", team: "cle", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 80.5, rec_yds: 1100.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Nico Collins", team: "hou", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 75.5, rec_yds: 1050.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Zay Flowers", team: "bal", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 50.5, rush_tds: 0.5, receptions: 80.5, rec_yds: 950.5, rec_tds: 6.5, fumbles: 1 },
    { name: "George Pickens", team: "pit", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 70.5, rec_yds: 1050.5, rec_tds: 6.5, fumbles: 1 },
    { name: "Rome Odunze", team: "chi", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 65.5, rec_yds: 850.5, rec_tds: 5.5, fumbles: 0 },
    { name: "Christian Kirk", team: "jax", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 80.5, rec_yds: 950.5, rec_tds: 6.5, fumbles: 1 },
    { name: "Tank Dell", team: "hou", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 70.5, rec_yds: 950.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Tee Higgins", team: "cin", position: "WR", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 75.5, rec_yds: 1050.5, rec_tds: 7.5, fumbles: 1 },
  
    // --- TIGHT ENDS ---
    { name: "Travis Kelce", team: "kc", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 90.5, rec_yds: 950.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Sam LaPorta", team: "det", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 88.5, rec_yds: 950.5, rec_tds: 8.5, fumbles: 0 },
    { name: "Mark Andrews", team: "bal", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 80.5, rec_yds: 900.5, rec_tds: 7.5, fumbles: 1 },
    { name: "Trey McBride", team: "ari", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 85.5, rec_yds: 900.5, rec_tds: 6.5, fumbles: 1 },
    { name: "Dalton Kincaid", team: "buf", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 80.5, rec_yds: 800.5, rec_tds: 6.5, fumbles: 1 },
    { name: "George Kittle", team: "sf", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 70.5, rec_yds: 900.5, rec_tds: 6.5, fumbles: 1 },
    { name: "Evan Engram", team: "jax", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 95.5, rec_yds: 850.5, rec_tds: 5.5, fumbles: 2 },
    { name: "David Njoku", team: "cle", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 75.5, rec_yds: 800.5, rec_tds: 6.5, fumbles: 1 },
    { name: "Kyle Pitts", team: "atl", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 70.5, rec_yds: 850.5, rec_tds: 5.5, fumbles: 1 },
    { name: "Jake Ferguson", team: "dal", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 70.5, rec_yds: 750.5, rec_tds: 6.5, fumbles: 0 },
    { name: "Dallas Goedert", team: "phi", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 0, rush_tds: 0, receptions: 65.5, rec_yds: 700.5, rec_tds: 5.5, fumbles: 1 },
    { name: "Brock Bowers", team: "lv", position: "TE", pass_yds: 0, pass_tds: 0, ints: 0, rush_yds: 25.5, rush_tds: 0.5, receptions: 65.5, rec_yds: 700.5, rec_tds: 5.5, fumbles: 1 }
  ];